GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/6304930480de1508b01c6815

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MzAxZGI3MTQwNjJiMGQzMzFhZDY2NGQiLCJpYXQiOjE2NjEwOTQwNDZ9.QR7p5Ybqb2A3l9p1z6g27QPiY1u07VCqXkYdC31DLM4

{
    "title": "55",
    "author": "55",
    "url": "55",
    "likes": 10
}

###
PUT http://localhost:3003/api/blogs/5a422aa71b54a676234d17f8
content-type: application/json

{
"title": "Go To Statement Considered Harmful",
"author": "Edsger W. Dijkstra",
"url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
"likes": 120,
"id": "5a422aa71b54a676234d17f8"
}

###
DELETE http://localhost:3003/api/blogs/6304a6763b2122c13395eed8
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2MzA0YTYzNDNiMjEyMmMxMzM5NWVlZDEiLCJpYXQiOjE2NjEyNDkxMDF9.tYFQstwgTObNNYiT83e4SyFhpatvYGaPC2XEhw52IHI


//for test populating and deleting all below
###
DELETE http://localhost:3003/api/blogs/devdelete

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test1",
    "author": "test1",
    "url": "test1",
    "likes": 10
}


###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test2",
    "author": "test2",
    "url": "test2",
    "likes": 10
}


###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test3",
    "author": "test3",
    "url": "test3",
    "likes": 10
}

///USER TESTING
###
GET http://localhost:3003/api/users


###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "user2",
    "name": "user2",
    "password": "user2"
}

###
//LOGIN
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "user2",
  "password": "user2"
}
