GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/6304930480de1508b01c6815

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MzA3MTQ3MWU3NWNjOGRkNDA4NWY5ZjUiLCJpYXQiOjE2NjE0MTIxNzR9.KILNjxOuniYggI92aUtiGlKoPDNgR-o0oNSHZ8efX8s

{
    "title": "blog3",
    "author": "blog3",
    "url": "blog3",
    "likes": 10
}

###
PUT http://localhost:3003/api/blogs/5a422aa71b54a676234d17f8
content-type: application/json

{
"title": "Go To Statement Considered Harmful",
"author": "Edsger W. Dijkstra",
"url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
"likes": 120,
"id": "5a422aa71b54a676234d17f8"
}

###
DELETE http://localhost:3003/api/blogs/630708020d16ccc4e51661ce
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MzA2ZTJlYTBkOGQxZWNiZmE5NGM4YmUiLCJpYXQiOjE2NjEzOTY5ODh9.1JBomvQMiudnFn5_y6Tb-gEmej15ZQ72-hR7iWjbgxU


//for test populating and deleting all below
###
DELETE http://localhost:3003/api/blogs/devdelete

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test1",
    "author": "test1",
    "url": "test1",
    "likes": 10
}


###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test2",
    "author": "test2",
    "url": "test2",
    "likes": 10
}


###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test3",
    "author": "test3",
    "url": "test3",
    "likes": 10
}

///USER TESTING
###
GET http://localhost:3003/api/users


###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "user1",
    "name": "user1",
    "password": "user1"
}

###
//LOGIN
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "user1",
  "password": "user1"
}
